---

classes:
    - metacpan::role::developer
    - metacpan::system::mongodb
    - metacpan_postgres

# Have to hard code `vagrant` or the dependency
# tree doesn't work
metacpan::tmp_dir: "/home/vagrant/tmp"
