---

classes:
    - metacpan::role::developer
    - metacpan::system::mongodb
    - metacpan_postgres

# Have to hard code `vagrant` or the dependency
# tree doesn't work
metacpan::tmp_dir: "/home/vagrant/tmp"

metacpan::elasticsearch::cluster_name: 'dev'
metacpan::elasticsearch::master_nodes: 1
metacpan::elasticsearch::expected_nodes: 1
metacpan::elasticsearch::replicas: 0
