---

classes:
    - metacpan::role::production
    - metacpan::system::mongodb

exim::config_type: 'satellite'
exim::smarthost: 'smtp.mailgun.org'
exim::relayhost: '*.mailgun.org'

metacpan::carton_args: '--deployment'

metacpan::elasticsearch::memory: '18g'

# We want watcher enabled
metacpan::watcher::enable: true

# Let's have rrr on all machines for now
# we can setup cpan.mc.org with a failover!
metacpan::rrrclient::enable: true

metacpan::crons::general:
    metacpan_clean_up_source:
      ensure : present

metacpan::web::starman:
  metacpan-web:
    git_enable: true
    starman_workers: 10
  metacpan-api:
    git_enable: true
    starman_workers: 14

  github-meets-cpan:
    git_source: 'https://github.com/CPAN-API/github-meets-cpan.git'
    git_revision: 'master'
    git_enable: true
    vhost_bare: true
    vhost_aliases:
      - 'gh.metacpan.org'
      - "gh.lo.metacpan.org"
      - "gh.%{hostname}.metacpan.org"
    starman_port: 5002
    starman_workers: 1

metacpan::web::static:
  metacpan-explorer:
    git_enable: true

metacpan::users:
    leo:
        admin    : true
        fullname : "Leo Lapworth <leo@cuckoo.org>"
        no_passwd_sudo : true
    clinton:
        admin    : true
        fullname : "Clinton Gormley <clint@traveljury.com>"
    mo:
        admin    : true
        fullname : "Moritz Onken <onken@netcubed.de>"
    olaf:
        admin    : true
        fullname : "Olaf Alders <olaf.alders@gmail.com>"
    rafl:
        admin    : true
        fullname : "Florian Ragwitz <rafl@perldition.org>"
        shell    : /bin/zsh
    rwstauner:
        admin    : true
        fullname : 'Randy Stauner <rwstauner@cpan.org>'
        shell    : /bin/zsh
    trs:
        admin    : true
        fullname : "Thomas Sibley <tsibley@cpan.org>"
    matthewt:
        admin    : true
        fullname : "Matt S Trout <perl-stuff@trout.me.uk>"
    haarg:
        admin    : true
        fullname : "Graham Knop <haarg@haarg.org>"
    mhorsfall:
        admin    : true
        fullname : "Matthew Horsfall (alh) <wolfsage@gmail.com>"
    ben:
        admin    : true
        fullname : "Ben Hundley <ben@qbox.io>"
